image: ubuntu:14.04
  
upload_egg:
  script:
    # add git as part of the egg upload
    - apt-get update -y && apt-get install -y git
    # Check if the package is actually installable
    - apt-get install -y python curl
    - apt-get install -y python-dev libffi-dev
    - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    - python get-pip.py
    - pip install pyOpenSSL ndg-httpsclient pyasn1
    - pip install -U devpi-client

    # make sure there's only 1 "version=" line in the setup.py file
    - (if [ "$(sed -n "/.*\(version\).*=.*\'.*/p" setup.py | sed -e 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/' | grep -v 'version' | wc -l)" == "1" ]; then echo "Found the version number"; else echo "Fail"; exit 33; fi);
    # update version to put custom ContextLogic version
    - version_origin=$(sed -n "/.*\(version\).*=.*\'.*/p" setup.py | sed -e 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/' | grep -v 'version')
    - version_cl="$version_origin+cl$CI_PIPELINE_ID"
    - sed -i "s/$version_origin/$version_cl/g" setup.py
    - pip install .
    - pip show TornadoAsyncMemcache

  #   # Upload to Wish Pypi
  #   - devpi use $PYPI_SERVER
  #   - devpi login $USERNAME --password=$PASSWORD
  #   - devpi use $INDEX
  #   - devpi upload
  # only:
  #   - master
